import { Country } from '../../models/location.model';

/**
 * Curated list of global countries with USA and Canada pinned at top for fast travel tracking.
 */
export const GLOBAL_COUNTRIES: Country[] = [
  // Pinned Primary Nations
  { id: 'US', code: 'US', name: 'United States', pinned: true },
  { id: 'CA', code: 'CA', name: 'Canada', pinned: true },

  // World Nations (alphabetical)
  { id: 'AF', code: 'AF', name: 'Afghanistan' },
  { id: 'AL', code: 'AL', name: 'Albania' },
  { id: 'DZ', code: 'DZ', name: 'Algeria' },
  { id: 'AD', code: 'AD', name: 'Andorra' },
  { id: 'AO', code: 'AO', name: 'Angola' },
  { id: 'AG', code: 'AG', name: 'Antigua and Barbuda' },
  { id: 'AR', code: 'AR', name: 'Argentina' },
  { id: 'AM', code: 'AM', name: 'Armenia' },
  { id: 'AU', code: 'AU', name: 'Australia' },
  { id: 'AT', code: 'AT', name: 'Austria' },
  { id: 'AZ', code: 'AZ', name: 'Azerbaijan' },
  { id: 'BS', code: 'BS', name: 'Bahamas' },
  { id: 'BH', code: 'BH', name: 'Bahrain' },
  { id: 'BD', code: 'BD', name: 'Bangladesh' },
  { id: 'BB', code: 'BB', name: 'Barbados' },
  { id: 'BY', code: 'BY', name: 'Belarus' },
  { id: 'BE', code: 'BE', name: 'Belgium' },
  { id: 'BZ', code: 'BZ', name: 'Belize' },
  { id: 'BJ', code: 'BJ', name: 'Benin' },
  { id: 'BT', code: 'BT', name: 'Bhutan' },
  { id: 'BO', code: 'BO', name: 'Bolivia' },
  { id: 'BA', code: 'BA', name: 'Bosnia and Herzegovina' },
  { id: 'BW', code: 'BW', name: 'Botswana' },
  { id: 'BR', code: 'BR', name: 'Brazil' },
  { id: 'BN', code: 'BN', name: 'Brunei' },
  { id: 'BG', code: 'BG', name: 'Bulgaria' },
  { id: 'BF', code: 'BF', name: 'Burkina Faso' },
  { id: 'BI', code: 'BI', name: 'Burundi' },
  { id: 'KH', code: 'KH', name: 'Cambodia' },
  { id: 'CM', code: 'CM', name: 'Cameroon' },
  { id: 'CV', code: 'CV', name: 'Cape Verde' },
  { id: 'CF', code: 'CF', name: 'Central African Republic' },
  { id: 'TD', code: 'TD', name: 'Chad' },
  { id: 'CL', code: 'CL', name: 'Chile' },
  { id: 'CN', code: 'CN', name: 'China' },
  { id: 'CO', code: 'CO', name: 'Colombia' },
  { id: 'KM', code: 'KM', name: 'Comoros' },
  { id: 'CR', code: 'CR', name: 'Costa Rica' },
  { id: 'HR', code: 'HR', name: 'Croatia' },
  { id: 'CU', code: 'CU', name: 'Cuba' },
  { id: 'CY', code: 'CY', name: 'Cyprus' },
  { id: 'CZ', code: 'CZ', name: 'Czech Republic' },
  { id: 'CD', code: 'CD', name: 'Democratic Republic of the Congo' },
  { id: 'DK', code: 'DK', name: 'Denmark' },
  { id: 'DJ', code: 'DJ', name: 'Djibouti' },
  { id: 'DM', code: 'DM', name: 'Dominica' },
  { id: 'DO', code: 'DO', name: 'Dominican Republic' },
  { id: 'EC', code: 'EC', name: 'Ecuador' },
  { id: 'EG', code: 'EG', name: 'Egypt' },
  { id: 'SV', code: 'SV', name: 'El Salvador' },
  { id: 'GQ', code: 'GQ', name: 'Equatorial Guinea' },
  { id: 'ER', code: 'ER', name: 'Eritrea' },
  { id: 'EE', code: 'EE', name: 'Estonia' },
  { id: 'SZ', code: 'SZ', name: 'Eswatini' },
  { id: 'ET', code: 'ET', name: 'Ethiopia' },
  { id: 'FJ', code: 'FJ', name: 'Fiji' },
  { id: 'FI', code: 'FI', name: 'Finland' },
  { id: 'FR', code: 'FR', name: 'France' },
  { id: 'GA', code: 'GA', name: 'Gabon' },
  { id: 'GM', code: 'GM', name: 'Gambia' },
  { id: 'GE', code: 'GE', name: 'Georgia' },
  { id: 'DE', code: 'DE', name: 'Germany' },
  { id: 'GH', code: 'GH', name: 'Ghana' },
  { id: 'GR', code: 'GR', name: 'Greece' },
  { id: 'GD', code: 'GD', name: 'Grenada' },
  { id: 'GT', code: 'GT', name: 'Guatemala' },
  { id: 'GN', code: 'GN', name: 'Guinea' },
  { id: 'GW', code: 'GW', name: 'Guinea-Bissau' },
  { id: 'GY', code: 'GY', name: 'Guyana' },
  { id: 'HT', code: 'HT', name: 'Haiti' },
  { id: 'HN', code: 'HN', name: 'Honduras' },
  { id: 'HU', code: 'HU', name: 'Hungary' },
  { id: 'IS', code: 'IS', name: 'Iceland' },
  { id: 'IN', code: 'IN', name: 'India' },
  { id: 'ID', code: 'ID', name: 'Indonesia' },
  { id: 'IR', code: 'IR', name: 'Iran' },
  { id: 'IQ', code: 'IQ', name: 'Iraq' },
  { id: 'IE', code: 'IE', name: 'Ireland' },
  { id: 'IL', code: 'IL', name: 'Israel' },
  { id: 'IT', code: 'IT', name: 'Italy' },
  { id: 'JM', code: 'JM', name: 'Jamaica' },
  { id: 'JP', code: 'JP', name: 'Japan' },
  { id: 'JO', code: 'JO', name: 'Jordan' },
  { id: 'KZ', code: 'KZ', name: 'Kazakhstan' },
  { id: 'KE', code: 'KE', name: 'Kenya' },
  { id: 'KI', code: 'KI', name: 'Kiribati' },
  { id: 'KW', code: 'KW', name: 'Kuwait' },
  { id: 'KG', code: 'KG', name: 'Kyrgyzstan' },
  { id: 'LA', code: 'LA', name: 'Laos' },
  { id: 'LV', code: 'LV', name: 'Latvia' },
  { id: 'LB', code: 'LB', name: 'Lebanon' },
  { id: 'LS', code: 'LS', name: 'Lesotho' },
  { id: 'LR', code: 'LR', name: 'Liberia' },
  { id: 'LY', code: 'LY', name: 'Libya' },
  { id: 'LI', code: 'LI', name: 'Liechtenstein' },
  { id: 'LT', code: 'LT', name: 'Lithuania' },
  { id: 'LU', code: 'LU', name: 'Luxembourg' },
  { id: 'MG', code: 'MG', name: 'Madagascar' },
  { id: 'MW', code: 'MW', name: 'Malawi' },
  { id: 'MY', code: 'MY', name: 'Malaysia' },
  { id: 'MV', code: 'MV', name: 'Maldives' },
  { id: 'ML', code: 'ML', name: 'Mali' },
  { id: 'MT', code: 'MT', name: 'Malta' },
  { id: 'MH', code: 'MH', name: 'Marshall Islands' },
  { id: 'MR', code: 'MR', name: 'Mauritania' },
  { id: 'MU', code: 'MU', name: 'Mauritius' },
  { id: 'MX', code: 'MX', name: 'Mexico' },
  { id: 'FM', code: 'FM', name: 'Micronesia' },
  { id: 'MD', code: 'MD', name: 'Moldova' },
  { id: 'MC', code: 'MC', name: 'Monaco' },
  { id: 'MN', code: 'MN', name: 'Mongolia' },
  { id: 'ME', code: 'ME', name: 'Montenegro' },
  { id: 'MA', code: 'MA', name: 'Morocco' },
  { id: 'MZ', code: 'MZ', name: 'Mozambique' },
  { id: 'MM', code: 'MM', name: 'Myanmar' },
  { id: 'NA', code: 'NA', name: 'Namibia' },
  { id: 'NR', code: 'NR', name: 'Nauru' },
  { id: 'NP', code: 'NP', name: 'Nepal' },
  { id: 'NL', code: 'NL', name: 'Netherlands' },
  { id: 'NZ', code: 'NZ', name: 'New Zealand' },
  { id: 'NI', code: 'NI', name: 'Nicaragua' },
  { id: 'NE', code: 'NE', name: 'Niger' },
  { id: 'NG', code: 'NG', name: 'Nigeria' },
  { id: 'MK', code: 'MK', name: 'North Macedonia' },
  { id: 'NO', code: 'NO', name: 'Norway' },
  { id: 'OM', code: 'OM', name: 'Oman' },
  { id: 'PK', code: 'PK', name: 'Pakistan' },
  { id: 'PW', code: 'PW', name: 'Palau' },
  { id: 'PA', code: 'PA', name: 'Panama' },
  { id: 'PG', code: 'PG', name: 'Papua New Guinea' },
  { id: 'PY', code: 'PY', name: 'Paraguay' },
  { id: 'PE', code: 'PE', name: 'Peru' },
  { id: 'PH', code: 'PH', name: 'Philippines' },
  { id: 'PL', code: 'PL', name: 'Poland' },
  { id: 'PT', code: 'PT', name: 'Portugal' },
  { id: 'QA', code: 'QA', name: 'Qatar' },
  { id: 'CG', code: 'CG', name: 'Republic of the Congo' },
  { id: 'RO', code: 'RO', name: 'Romania' },
  { id: 'RU', code: 'RU', name: 'Russia' },
  { id: 'RW', code: 'RW', name: 'Rwanda' },
  { id: 'KN', code: 'KN', name: 'Saint Kitts and Nevis' },
  { id: 'LC', code: 'LC', name: 'Saint Lucia' },
  { id: 'VC', code: 'VC', name: 'Saint Vincent and the Grenadines' },
  { id: 'WS', code: 'WS', name: 'Samoa' },
  { id: 'SM', code: 'SM', name: 'San Marino' },
  { id: 'ST', code: 'ST', name: 'Sao Tome and Principe' },
  { id: 'SA', code: 'SA', name: 'Saudi Arabia' },
  { id: 'SN', code: 'SN', name: 'Senegal' },
  { id: 'RS', code: 'RS', name: 'Serbia' },
  { id: 'SC', code: 'SC', name: 'Seychelles' },
  { id: 'SL', code: 'SL', name: 'Sierra Leone' },
  { id: 'SG', code: 'SG', name: 'Singapore' },
  { id: 'SK', code: 'SK', name: 'Slovakia' },
  { id: 'SI', code: 'SI', name: 'Slovenia' },
  { id: 'SB', code: 'SB', name: 'Solomon Islands' },
  { id: 'SO', code: 'SO', name: 'Somalia' },
  { id: 'ZA', code: 'ZA', name: 'South Africa' },
  { id: 'KR', code: 'KR', name: 'South Korea' },
  { id: 'SS', code: 'SS', name: 'South Sudan' },
  { id: 'ES', code: 'ES', name: 'Spain' },
  { id: 'LK', code: 'LK', name: 'Sri Lanka' },
  { id: 'SD', code: 'SD', name: 'Sudan' },
  { id: 'SR', code: 'SR', name: 'Suriname' },
  { id: 'SE', code: 'SE', name: 'Sweden' },
  { id: 'CH', code: 'CH', name: 'Switzerland' },
  { id: 'SY', code: 'SY', name: 'Syria' },
  { id: 'TW', code: 'TW', name: 'Taiwan' },
  { id: 'TJ', code: 'TJ', name: 'Tajikistan' },
  { id: 'TZ', code: 'TZ', name: 'Tanzania' },
  { id: 'TH', code: 'TH', name: 'Thailand' },
  { id: 'TL', code: 'TL', name: 'Timor-Leste' },
  { id: 'TG', code: 'TG', name: 'Togo' },
  { id: 'TO', code: 'TO', name: 'Tonga' },
  { id: 'TT', code: 'TT', name: 'Trinidad and Tobago' },
  { id: 'TN', code: 'TN', name: 'Tunisia' },
  { id: 'TR', code: 'TR', name: 'Turkey' },
  { id: 'TM', code: 'TM', name: 'Turkmenistan' },
  { id: 'TV', code: 'TV', name: 'Tuvalu' },
  { id: 'UG', code: 'UG', name: 'Uganda' },
  { id: 'UA', code: 'UA', name: 'Ukraine' },
  { id: 'AE', code: 'AE', name: 'United Arab Emirates' },
  { id: 'GB', code: 'GB', name: 'United Kingdom' },
  { id: 'UY', code: 'UY', name: 'Uruguay' },
  { id: 'UZ', code: 'UZ', name: 'Uzbekistan' },
  { id: 'VU', code: 'VU', name: 'Vanuatu' },
  { id: 'VA', code: 'VA', name: 'Vatican City' },
  { id: 'VE', code: 'VE', name: 'Venezuela' },
  { id: 'VN', code: 'VN', name: 'Vietnam' },
  { id: 'YE', code: 'YE', name: 'Yemen' },
  { id: 'ZM', code: 'ZM', name: 'Zambia' },
  { id: 'ZW', code: 'ZW', name: 'Zimbabwe' },
];

export const COUNTRIES_MAP = new Map<string, Country>(GLOBAL_COUNTRIES.map((c) => [c.id, c]));
