import { Place } from '../../models/location.model';
import { NATIONAL_PARKS } from './geography.constants';

/**
 * Curated US and Canadian National Parks mapped as Place entities.
 */
export const CURATED_NATIONAL_PARKS: Place[] = NATIONAL_PARKS.map((p) => {
  const isCanada = p.country === 'Canada';
  const countryId = isCanada ? 'CA' : 'US';
  const primarySub = p.sub ? p.sub.split('/')[0] : '';
  const regionId = primarySub ? `${countryId}-${primarySub}` : undefined;
  const slug = 'np-' + p.id.toLowerCase().replace(/[^a-z0-9]+/g, '-');
  return {
    id: slug,
    name:
      p.name.includes('Park') || p.name.includes('Preserve') ? p.name : `${p.name} National Park`,
    category: 'national_park',
    countryId,
    regionId,
    lat: p.lat,
    lng: p.lng,
    source: 'static',
    isCurated: true,
    tags: ['national_park', 'nature', 'scenic'],
  };
});

/**
 * Curated "Crown Jewels" State and Provincial Parks.
 * Represents top-tier, famous, heavily visited public parks.
 */
export const CROWN_JEWELS_STATE_PARKS: Place[] = [
  // United States "Crown Jewels" State Parks
  {
    id: 'sp-adirondack',
    name: 'Adirondack Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-NY',
    lat: 43.85,
    lng: -74.45,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'hiking', 'camping', 'scenic'],
  },
  {
    id: 'sp-niagara-falls',
    name: 'Niagara Falls State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-NY',
    lat: 43.0828,
    lng: -79.0647,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'scenic', 'historic'],
  },
  {
    id: 'sp-watkins-glen',
    name: 'Watkins Glen State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-NY',
    lat: 42.3764,
    lng: -76.8724,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'hiking', 'scenic', 'waterfalls'],
  },
  {
    id: 'sp-custer',
    name: 'Custer State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-SD',
    lat: 43.7667,
    lng: -103.5333,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'wildlife', 'scenic', 'camping'],
  },
  {
    id: 'sp-starved-rock',
    name: 'Starved Rock State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-IL',
    lat: 41.3206,
    lng: -88.9928,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'hiking', 'scenic', 'canyons'],
  },
  {
    id: 'sp-valley-of-fire',
    name: 'Valley of Fire State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-NV',
    lat: 36.4564,
    lng: -114.5333,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'scenic', 'desert', 'hiking'],
  },
  {
    id: 'sp-anza-borrego',
    name: 'Anza-Borrego Desert State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-CA',
    lat: 33.2569,
    lng: -116.4069,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'desert', 'camping', 'scenic'],
  },
  {
    id: 'sp-emerald-bay',
    name: 'Emerald Bay State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-CA',
    lat: 38.9542,
    lng: -120.1003,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'scenic', 'lake', 'hiking'],
  },
  {
    id: 'sp-julia-pfeiffer-burns',
    name: 'Julia Pfeiffer Burns State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-CA',
    lat: 36.1583,
    lng: -121.6706,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'coastal', 'scenic', 'waterfalls'],
  },
  {
    id: 'sp-prairie-creek-redwoods',
    name: 'Prairie Creek Redwoods State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-CA',
    lat: 41.3639,
    lng: -124.0231,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'redwoods', 'coastal', 'hiking', 'scenic'],
  },
  {
    id: 'sp-jedediah-smith-redwoods',
    name: 'Jedediah Smith Redwoods State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-CA',
    lat: 41.7964,
    lng: -124.0847,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'redwoods', 'coastal', 'scenic'],
  },
  {
    id: 'sp-humboldt-redwoods',
    name: 'Humboldt Redwoods State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-CA',
    lat: 40.3156,
    lng: -123.9189,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'redwoods', 'scenic'],
  },
  {
    id: 'sp-baxter',
    name: 'Baxter State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-ME',
    lat: 45.9222,
    lng: -68.9167,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'hiking', 'mountains', 'wilderness'],
  },
  {
    id: 'sp-fall-creek-falls',
    name: 'Fall Creek Falls State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-TN',
    lat: 35.6603,
    lng: -85.3522,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'waterfalls', 'camping', 'hiking'],
  },
  {
    id: 'sp-mackinac-island',
    name: 'Mackinac Island State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-MI',
    lat: 45.8672,
    lng: -84.6289,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'historic', 'scenic', 'island'],
  },
  {
    id: 'sp-porcupine-mountains',
    name: 'Porcupine Mountains Wilderness State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-MI',
    lat: 46.8042,
    lng: -89.7828,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'hiking', 'wilderness', 'scenic'],
  },
  {
    id: 'sp-ludington',
    name: 'Ludington State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-MI',
    lat: 44.0256,
    lng: -86.5056,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'beach', 'dunes', 'camping'],
  },
  {
    id: 'sp-goblin-valley',
    name: 'Goblin Valley State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-UT',
    lat: 38.5667,
    lng: -110.7,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'desert', 'scenic', 'hiking'],
  },
  {
    id: 'sp-dead-horse-point',
    name: 'Dead Horse Point State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-UT',
    lat: 38.4908,
    lng: -109.7397,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'scenic', 'canyon'],
  },
  {
    id: 'sp-hocking-hills',
    name: 'Hocking Hills State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-OH',
    lat: 39.4347,
    lng: -82.5378,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'caves', 'waterfalls', 'hiking'],
  },
  {
    id: 'sp-devils-lake',
    name: "Devil's Lake State Park",
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-WI',
    lat: 43.4217,
    lng: -89.7314,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'hiking', 'climbing', 'lake'],
  },
  {
    id: 'sp-peninsula',
    name: 'Peninsula State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-WI',
    lat: 45.1583,
    lng: -87.1861,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'camping', 'scenic', 'biking'],
  },
  {
    id: 'sp-itasca',
    name: 'Itasca State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-MN',
    lat: 47.2389,
    lng: -95.2056,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'historic', 'nature', 'camping'],
  },
  {
    id: 'sp-silver-falls',
    name: 'Silver Falls State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-OR',
    lat: 44.8783,
    lng: -122.6517,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'waterfalls', 'hiking', 'scenic'],
  },
  {
    id: 'sp-ecola',
    name: 'Ecola State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-OR',
    lat: 45.9228,
    lng: -123.9744,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'coastal', 'scenic', 'hiking'],
  },
  {
    id: 'sp-smith-rock',
    name: 'Smith Rock State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-OR',
    lat: 44.3683,
    lng: -121.1406,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'hiking', 'climbing', 'scenic'],
  },
  {
    id: 'sp-deception-pass',
    name: 'Deception Pass State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-WA',
    lat: 48.4042,
    lng: -122.6456,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'coastal', 'scenic', 'camping'],
  },
  {
    id: 'sp-beacon-rock',
    name: 'Beacon Rock State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-WA',
    lat: 45.6289,
    lng: -122.0222,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'hiking', 'columbia_gorge', 'scenic'],
  },
  {
    id: 'sp-palo-duro',
    name: 'Palo Duro Canyon State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-TX',
    lat: 34.9392,
    lng: -101.6606,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'canyon', 'hiking', 'camping'],
  },
  {
    id: 'sp-makoshika',
    name: 'Makoshika State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-MT',
    lat: 47.0944,
    lng: -104.6889,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'badlands', 'paleontology', 'scenic'],
  },
  {
    id: 'sp-chugach',
    name: 'Chugach State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-AK',
    lat: 61.2667,
    lng: -149.3167,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'mountains', 'hiking', 'wilderness'],
  },
  {
    id: 'sp-franconia-notch',
    name: 'Franconia Notch State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-NH',
    lat: 44.1481,
    lng: -71.6889,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'mountains', 'hiking', 'scenic'],
  },
  {
    id: 'sp-presque-isle',
    name: 'Presque Isle State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-PA',
    lat: 42.1583,
    lng: -80.125,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'beach', 'lake_erie', 'birding'],
  },
  {
    id: 'sp-bahia-honda',
    name: 'Bahia Honda State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-FL',
    lat: 24.6617,
    lng: -81.2789,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'beach', 'florida_keys', 'snorkeling'],
  },
  {
    id: 'sp-waimea-canyon',
    name: 'Waimea Canyon State Park',
    category: 'state_park',
    countryId: 'US',
    regionId: 'US-HI',
    lat: 22.0833,
    lng: -159.6667,
    source: 'static',
    isCurated: true,
    tags: ['state_park', 'canyon', 'scenic', 'hawaii'],
  },

  // Canada Provincial Parks "Crown Jewels"
  {
    id: 'pp-algonquin',
    name: 'Algonquin Provincial Park',
    category: 'provincial_park',
    countryId: 'CA',
    regionId: 'CA-ON',
    lat: 45.5536,
    lng: -78.5964,
    source: 'static',
    isCurated: true,
    tags: ['provincial_park', 'canoeing', 'camping', 'wildlife'],
  },
  {
    id: 'pp-kananaskis',
    name: 'Peter Lougheed / Kananaskis Provincial Park',
    category: 'provincial_park',
    countryId: 'CA',
    regionId: 'CA-AB',
    lat: 50.635,
    lng: -115.15,
    source: 'static',
    isCurated: true,
    tags: ['provincial_park', 'rockies', 'hiking', 'scenic'],
  },
  {
    id: 'pp-dinosaur',
    name: 'Dinosaur Provincial Park',
    category: 'provincial_park',
    countryId: 'CA',
    regionId: 'CA-AB',
    lat: 50.7558,
    lng: -111.5186,
    source: 'static',
    isCurated: true,
    tags: ['provincial_park', 'badlands', 'unesco', 'fossils'],
  },
  {
    id: 'pp-strathcona',
    name: 'Strathcona Provincial Park',
    category: 'provincial_park',
    countryId: 'CA',
    regionId: 'CA-BC',
    lat: 49.7167,
    lng: -125.6833,
    source: 'static',
    isCurated: true,
    tags: ['provincial_park', 'vancouver_island', 'hiking', 'mountains'],
  },
  {
    id: 'pp-mont-tremblant',
    name: 'Parc National du Mont-Tremblant',
    category: 'provincial_park',
    countryId: 'CA',
    regionId: 'CA-QC',
    lat: 46.3333,
    lng: -74.4167,
    source: 'static',
    isCurated: true,
    tags: ['provincial_park', 'mountains', 'hiking', 'lakes'],
  },
  {
    id: 'pp-sandbanks',
    name: 'Sandbanks Provincial Park',
    category: 'provincial_park',
    countryId: 'CA',
    regionId: 'CA-ON',
    lat: 43.9167,
    lng: -77.2667,
    source: 'static',
    isCurated: true,
    tags: ['provincial_park', 'beach', 'dunes', 'camping'],
  },
];

/**
 * Curated Key Cities (Capitals & Major Metropolitan Tourist/Economic Hubs).
 */
export const CURATED_CITIES: Place[] = [
  // United States Capitals (National + 50 State Capitals)
  {
    id: 'city-washington-dc',
    name: 'Washington, D.C.',
    category: 'city',
    countryId: 'US',
    regionId: 'US-DC',
    lat: 38.9072,
    lng: -77.0369,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'historic', 'museums'],
  },
  {
    id: 'city-montgomery',
    name: 'Montgomery',
    category: 'city',
    countryId: 'US',
    regionId: 'US-AL',
    lat: 32.377,
    lng: -86.3006,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-juneau',
    name: 'Juneau',
    category: 'city',
    countryId: 'US',
    regionId: 'US-AK',
    lat: 58.3019,
    lng: -134.4197,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-phoenix',
    name: 'Phoenix',
    category: 'city',
    countryId: 'US',
    regionId: 'US-AZ',
    lat: 33.4484,
    lng: -112.074,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-little-rock',
    name: 'Little Rock',
    category: 'city',
    countryId: 'US',
    regionId: 'US-AR',
    lat: 34.7465,
    lng: -92.2896,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-sacramento',
    name: 'Sacramento',
    category: 'city',
    countryId: 'US',
    regionId: 'US-CA',
    lat: 38.5816,
    lng: -121.4944,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-denver',
    name: 'Denver',
    category: 'city',
    countryId: 'US',
    regionId: 'US-CO',
    lat: 39.7392,
    lng: -104.9903,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-hartford',
    name: 'Hartford',
    category: 'city',
    countryId: 'US',
    regionId: 'US-CT',
    lat: 41.7658,
    lng: -72.6734,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-dover',
    name: 'Dover',
    category: 'city',
    countryId: 'US',
    regionId: 'US-DE',
    lat: 39.1582,
    lng: -75.5244,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-tallahassee',
    name: 'Tallahassee',
    category: 'city',
    countryId: 'US',
    regionId: 'US-FL',
    lat: 30.4383,
    lng: -84.2807,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-atlanta',
    name: 'Atlanta',
    category: 'city',
    countryId: 'US',
    regionId: 'US-GA',
    lat: 33.749,
    lng: -84.388,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-honolulu',
    name: 'Honolulu',
    category: 'city',
    countryId: 'US',
    regionId: 'US-HI',
    lat: 21.3069,
    lng: -157.8583,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'beach'],
  },
  {
    id: 'city-boise',
    name: 'Boise',
    category: 'city',
    countryId: 'US',
    regionId: 'US-ID',
    lat: 43.615,
    lng: -116.2023,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-springfield-il',
    name: 'Springfield',
    category: 'city',
    countryId: 'US',
    regionId: 'US-IL',
    lat: 39.7817,
    lng: -89.6501,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-indianapolis',
    name: 'Indianapolis',
    category: 'city',
    countryId: 'US',
    regionId: 'US-IN',
    lat: 39.7684,
    lng: -86.1581,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-des-moines',
    name: 'Des Moines',
    category: 'city',
    countryId: 'US',
    regionId: 'US-IA',
    lat: 41.5868,
    lng: -93.625,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-topeka',
    name: 'Topeka',
    category: 'city',
    countryId: 'US',
    regionId: 'US-KS',
    lat: 39.0473,
    lng: -95.6752,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-frankfort',
    name: 'Frankfort',
    category: 'city',
    countryId: 'US',
    regionId: 'US-KY',
    lat: 38.2009,
    lng: -84.8733,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-baton-rouge',
    name: 'Baton Rouge',
    category: 'city',
    countryId: 'US',
    regionId: 'US-LA',
    lat: 30.4515,
    lng: -91.1871,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-augusta',
    name: 'Augusta',
    category: 'city',
    countryId: 'US',
    regionId: 'US-ME',
    lat: 44.3106,
    lng: -69.7795,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-annapolis',
    name: 'Annapolis',
    category: 'city',
    countryId: 'US',
    regionId: 'US-MD',
    lat: 38.9784,
    lng: -76.4922,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital', 'historic'],
  },
  {
    id: 'city-boston',
    name: 'Boston',
    category: 'city',
    countryId: 'US',
    regionId: 'US-MA',
    lat: 42.3601,
    lng: -71.0589,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'historic'],
  },
  {
    id: 'city-lansing',
    name: 'Lansing',
    category: 'city',
    countryId: 'US',
    regionId: 'US-MI',
    lat: 42.7325,
    lng: -84.5555,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-saint-paul',
    name: 'Saint Paul',
    category: 'city',
    countryId: 'US',
    regionId: 'US-MN',
    lat: 44.9537,
    lng: -93.09,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-jackson',
    name: 'Jackson',
    category: 'city',
    countryId: 'US',
    regionId: 'US-MS',
    lat: 32.2988,
    lng: -90.1848,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-jefferson-city',
    name: 'Jefferson City',
    category: 'city',
    countryId: 'US',
    regionId: 'US-MO',
    lat: 38.5767,
    lng: -92.1735,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-helena',
    name: 'Helena',
    category: 'city',
    countryId: 'US',
    regionId: 'US-MT',
    lat: 46.5891,
    lng: -112.0391,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-lincoln',
    name: 'Lincoln',
    category: 'city',
    countryId: 'US',
    regionId: 'US-NE',
    lat: 40.8136,
    lng: -96.7026,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-carson-city',
    name: 'Carson City',
    category: 'city',
    countryId: 'US',
    regionId: 'US-NV',
    lat: 39.1638,
    lng: -119.7674,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-concord',
    name: 'Concord',
    category: 'city',
    countryId: 'US',
    regionId: 'US-NH',
    lat: 43.2081,
    lng: -71.5376,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-trenton',
    name: 'Trenton',
    category: 'city',
    countryId: 'US',
    regionId: 'US-NJ',
    lat: 40.2206,
    lng: -74.7597,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-santa-fe',
    name: 'Santa Fe',
    category: 'city',
    countryId: 'US',
    regionId: 'US-NM',
    lat: 35.687,
    lng: -105.9378,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital', 'arts'],
  },
  {
    id: 'city-albany',
    name: 'Albany',
    category: 'city',
    countryId: 'US',
    regionId: 'US-NY',
    lat: 42.6526,
    lng: -73.7562,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-raleigh',
    name: 'Raleigh',
    category: 'city',
    countryId: 'US',
    regionId: 'US-NC',
    lat: 35.7796,
    lng: -78.6382,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-bismarck',
    name: 'Bismarck',
    category: 'city',
    countryId: 'US',
    regionId: 'US-ND',
    lat: 46.8083,
    lng: -100.7837,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-columbus',
    name: 'Columbus',
    category: 'city',
    countryId: 'US',
    regionId: 'US-OH',
    lat: 39.9612,
    lng: -82.9988,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-oklahoma-city',
    name: 'Oklahoma City',
    category: 'city',
    countryId: 'US',
    regionId: 'US-OK',
    lat: 35.4676,
    lng: -97.5164,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-salem',
    name: 'Salem',
    category: 'city',
    countryId: 'US',
    regionId: 'US-OR',
    lat: 44.9429,
    lng: -123.0351,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-harrisburg',
    name: 'Harrisburg',
    category: 'city',
    countryId: 'US',
    regionId: 'US-PA',
    lat: 40.2732,
    lng: -76.8867,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-providence',
    name: 'Providence',
    category: 'city',
    countryId: 'US',
    regionId: 'US-RI',
    lat: 41.824,
    lng: -71.4128,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-columbia',
    name: 'Columbia',
    category: 'city',
    countryId: 'US',
    regionId: 'US-SC',
    lat: 34.0007,
    lng: -81.0348,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-pierre',
    name: 'Pierre',
    category: 'city',
    countryId: 'US',
    regionId: 'US-SD',
    lat: 44.3683,
    lng: -100.351,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-nashville',
    name: 'Nashville',
    category: 'city',
    countryId: 'US',
    regionId: 'US-TN',
    lat: 36.1627,
    lng: -86.7816,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'music'],
  },
  {
    id: 'city-austin',
    name: 'Austin',
    category: 'city',
    countryId: 'US',
    regionId: 'US-TX',
    lat: 30.2672,
    lng: -97.7431,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'live_music'],
  },
  {
    id: 'city-salt-lake-city',
    name: 'Salt Lake City',
    category: 'city',
    countryId: 'US',
    regionId: 'US-UT',
    lat: 40.7608,
    lng: -111.891,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'skiing'],
  },
  {
    id: 'city-montpelier',
    name: 'Montpelier',
    category: 'city',
    countryId: 'US',
    regionId: 'US-VT',
    lat: 44.2601,
    lng: -72.5754,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-richmond',
    name: 'Richmond',
    category: 'city',
    countryId: 'US',
    regionId: 'US-VA',
    lat: 37.5407,
    lng: -77.436,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'historic'],
  },
  {
    id: 'city-olympia',
    name: 'Olympia',
    category: 'city',
    countryId: 'US',
    regionId: 'US-WA',
    lat: 47.0379,
    lng: -122.9007,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-charleston',
    name: 'Charleston',
    category: 'city',
    countryId: 'US',
    regionId: 'US-WV',
    lat: 38.3498,
    lng: -81.6326,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-madison',
    name: 'Madison',
    category: 'city',
    countryId: 'US',
    regionId: 'US-WI',
    lat: 43.0731,
    lng: -89.4012,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-cheyenne',
    name: 'Cheyenne',
    category: 'city',
    countryId: 'US',
    regionId: 'US-WY',
    lat: 41.14,
    lng: -104.8202,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },

  // US Major Metros
  {
    id: 'city-new-york',
    name: 'New York City',
    category: 'city',
    countryId: 'US',
    regionId: 'US-NY',
    lat: 40.7128,
    lng: -74.006,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'arts', 'dining'],
  },
  {
    id: 'city-los-angeles',
    name: 'Los Angeles',
    category: 'city',
    countryId: 'US',
    regionId: 'US-CA',
    lat: 34.0522,
    lng: -118.2437,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'entertainment', 'beach'],
  },
  {
    id: 'city-chicago',
    name: 'Chicago',
    category: 'city',
    countryId: 'US',
    regionId: 'US-IL',
    lat: 41.8781,
    lng: -87.6298,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'architecture', 'museums'],
  },
  {
    id: 'city-houston',
    name: 'Houston',
    category: 'city',
    countryId: 'US',
    regionId: 'US-TX',
    lat: 29.7604,
    lng: -95.3698,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'space', 'dining'],
  },
  {
    id: 'city-philadelphia',
    name: 'Philadelphia',
    category: 'city',
    countryId: 'US',
    regionId: 'US-PA',
    lat: 39.9526,
    lng: -75.1652,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'historic'],
  },
  {
    id: 'city-san-antonio',
    name: 'San Antonio',
    category: 'city',
    countryId: 'US',
    regionId: 'US-TX',
    lat: 29.4241,
    lng: -98.4936,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'historic', 'riverwalk'],
  },
  {
    id: 'city-san-diego',
    name: 'San Diego',
    category: 'city',
    countryId: 'US',
    regionId: 'US-CA',
    lat: 32.7157,
    lng: -117.1611,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'beach', 'zoo'],
  },
  {
    id: 'city-dallas',
    name: 'Dallas',
    category: 'city',
    countryId: 'US',
    regionId: 'US-TX',
    lat: 32.7767,
    lng: -96.797,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'dining'],
  },
  {
    id: 'city-san-francisco',
    name: 'San Francisco',
    category: 'city',
    countryId: 'US',
    regionId: 'US-CA',
    lat: 37.7749,
    lng: -122.4194,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'scenic', 'tech'],
  },
  {
    id: 'city-seattle',
    name: 'Seattle',
    category: 'city',
    countryId: 'US',
    regionId: 'US-WA',
    lat: 47.6062,
    lng: -122.3321,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'coffee', 'scenic'],
  },
  {
    id: 'city-miami',
    name: 'Miami',
    category: 'city',
    countryId: 'US',
    regionId: 'US-FL',
    lat: 25.7617,
    lng: -80.1918,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'beach', 'nightlife'],
  },
  {
    id: 'city-las-vegas',
    name: 'Las Vegas',
    category: 'city',
    countryId: 'US',
    regionId: 'US-NV',
    lat: 36.1699,
    lng: -115.1398,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'entertainment', 'resorts'],
  },
  {
    id: 'city-new-orleans',
    name: 'New Orleans',
    category: 'city',
    countryId: 'US',
    regionId: 'US-LA',
    lat: 29.9511,
    lng: -90.0715,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'music', 'dining', 'historic'],
  },
  {
    id: 'city-portland',
    name: 'Portland',
    category: 'city',
    countryId: 'US',
    regionId: 'US-OR',
    lat: 45.5152,
    lng: -122.6784,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'parks', 'food_trucks'],
  },

  // Canada Capitals & Major Metros
  {
    id: 'city-ottawa',
    name: 'Ottawa',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-ON',
    lat: 45.4215,
    lng: -75.6972,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'historic'],
  },
  {
    id: 'city-edmonton',
    name: 'Edmonton',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-AB',
    lat: 53.5461,
    lng: -113.4938,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-victoria',
    name: 'Victoria',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-BC',
    lat: 48.4284,
    lng: -123.3656,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital', 'scenic'],
  },
  {
    id: 'city-winnipeg',
    name: 'Winnipeg',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-MB',
    lat: 49.8951,
    lng: -97.1384,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-fredericton',
    name: 'Fredericton',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-NB',
    lat: 45.9636,
    lng: -66.6431,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-st-johns',
    name: "St. John's",
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-NL',
    lat: 47.5615,
    lng: -52.7126,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital', 'coastal'],
  },
  {
    id: 'city-halifax',
    name: 'Halifax',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-NS',
    lat: 44.6488,
    lng: -63.5752,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'coastal'],
  },
  {
    id: 'city-toronto',
    name: 'Toronto',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-ON',
    lat: 43.6532,
    lng: -79.3832,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'culture'],
  },
  {
    id: 'city-charlottetown',
    name: 'Charlottetown',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-PE',
    lat: 46.2382,
    lng: -63.1311,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-quebec-city',
    name: 'Quebec City',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-QC',
    lat: 46.8139,
    lng: -71.208,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'historic'],
  },
  {
    id: 'city-regina',
    name: 'Regina',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-SK',
    lat: 50.4547,
    lng: -104.6067,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-yellowknife',
    name: 'Yellowknife',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-NT',
    lat: 62.454,
    lng: -114.3718,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital', 'aurora'],
  },
  {
    id: 'city-iqaluit',
    name: 'Iqaluit',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-NU',
    lat: 63.7467,
    lng: -68.517,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital', 'arctic'],
  },
  {
    id: 'city-whitehorse',
    name: 'Whitehorse',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-YT',
    lat: 60.7212,
    lng: -135.0568,
    source: 'static',
    isCurated: true,
    isCapital: true,
    tags: ['city', 'capital', 'wilderness'],
  },
  {
    id: 'city-montreal',
    name: 'Montreal',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-QC',
    lat: 45.5017,
    lng: -73.5673,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'culture', 'dining'],
  },
  {
    id: 'city-vancouver',
    name: 'Vancouver',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-BC',
    lat: 49.2827,
    lng: -123.1207,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'scenic', 'mountains', 'ocean'],
  },
  {
    id: 'city-calgary',
    name: 'Calgary',
    category: 'city',
    countryId: 'CA',
    regionId: 'CA-AB',
    lat: 51.0447,
    lng: -114.0719,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'rockies', 'stampede'],
  },

  // World Key Capitals & Hubs
  {
    id: 'city-london',
    name: 'London',
    category: 'city',
    countryId: 'GB',
    lat: 51.5074,
    lng: -0.1278,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'historic'],
  },
  {
    id: 'city-paris',
    name: 'Paris',
    category: 'city',
    countryId: 'FR',
    lat: 48.8566,
    lng: 2.3522,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'art', 'dining'],
  },
  {
    id: 'city-rome',
    name: 'Rome',
    category: 'city',
    countryId: 'IT',
    lat: 41.9028,
    lng: 12.4964,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'historic'],
  },
  {
    id: 'city-tokyo',
    name: 'Tokyo',
    category: 'city',
    countryId: 'JP',
    lat: 35.6762,
    lng: 139.6503,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'technology'],
  },
  {
    id: 'city-berlin',
    name: 'Berlin',
    category: 'city',
    countryId: 'DE',
    lat: 52.52,
    lng: 13.405,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'culture'],
  },
  {
    id: 'city-madrid',
    name: 'Madrid',
    category: 'city',
    countryId: 'ES',
    lat: 40.4168,
    lng: -3.7038,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital'],
  },
  {
    id: 'city-amsterdam',
    name: 'Amsterdam',
    category: 'city',
    countryId: 'NL',
    lat: 52.3676,
    lng: 4.9041,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'canals'],
  },
  {
    id: 'city-dublin',
    name: 'Dublin',
    category: 'city',
    countryId: 'IE',
    lat: 53.3498,
    lng: -6.2603,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'pub'],
  },
  {
    id: 'city-sydney',
    name: 'Sydney',
    category: 'city',
    countryId: 'AU',
    lat: -33.8688,
    lng: 151.2093,
    source: 'static',
    isCurated: true,
    isMajorCity: true,
    tags: ['city', 'harbor', 'beach'],
  },
  {
    id: 'city-mexico-city',
    name: 'Mexico City',
    category: 'city',
    countryId: 'MX',
    lat: 19.4326,
    lng: -99.1332,
    source: 'static',
    isCurated: true,
    isCapital: true,
    isMajorCity: true,
    tags: ['city', 'capital', 'historic'],
  },
];

/**
 * Unified static places catalog combining curated National Parks,
 * Crown Jewels State/Provincial Parks, and Key Cities.
 */
export const STATIC_PLACES_CATALOG: Place[] = [
  ...CURATED_NATIONAL_PARKS,
  ...CROWN_JEWELS_STATE_PARKS,
  ...CURATED_CITIES,
];

/**
 * Fast O(1) in-memory lookup map for all static places.
 * Indexed by primary Place ID (e.g., 'np-yosemite', 'city-chicago') as well as
 * legacy / canonical names for seamless lookup.
 */
export const STATIC_PLACES_MAP = new Map<string, Place>();

// Populate primary and alias keys
for (const place of STATIC_PLACES_CATALOG) {
  STATIC_PLACES_MAP.set(place.id, place);
  // Also register normalized name as an alias if not colliding
  const nameKey = place.name.toLowerCase().trim();
  if (!STATIC_PLACES_MAP.has(nameKey)) {
    STATIC_PLACES_MAP.set(nameKey, place);
  }
}

/**
 * Look up a static place by id or name in O(1) time.
 */
export function getStaticPlace(idOrName: string): Place | undefined {
  if (!idOrName) return undefined;
  return STATIC_PLACES_MAP.get(idOrName) || STATIC_PLACES_MAP.get(idOrName.toLowerCase().trim());
}
