export interface GeoLocation {
  id: string; // Using name as ID for legacy compatibility
  name: string;
  lat: number;
  lng: number;
  sub?: string;
  country?: string;
  capital?: string;
}

export const NATIONAL_PARKS: GeoLocation[] = [
  { id: 'Acadia', name: 'Acadia', sub: 'ME', country: 'USA', lat: 44.3386, lng: -68.2733 },
  {
    id: 'American Samoa',
    name: 'American Samoa',
    sub: 'AS',
    country: 'USA',
    lat: -14.2583,
    lng: -170.6833,
  },
  { id: 'Arches', name: 'Arches', sub: 'UT', country: 'USA', lat: 38.7331, lng: -109.5925 },
  { id: 'Badlands', name: 'Badlands', sub: 'SD', country: 'USA', lat: 43.8554, lng: -102.3397 },
  { id: 'Big Bend', name: 'Big Bend', sub: 'TX', country: 'USA', lat: 29.1275, lng: -103.2425 },
  { id: 'Biscayne', name: 'Biscayne', sub: 'FL', country: 'USA', lat: 25.4824, lng: -80.1601 },
  {
    id: 'Black Canyon of the Gunnison',
    name: 'Black Canyon of the Gunnison',
    sub: 'CO',
    country: 'USA',
    lat: 38.5754,
    lng: -107.7416,
  },
  {
    id: 'Bryce Canyon',
    name: 'Bryce Canyon',
    sub: 'UT',
    country: 'USA',
    lat: 37.593,
    lng: -112.1871,
  },
  {
    id: 'Canyonlands',
    name: 'Canyonlands',
    sub: 'UT',
    country: 'USA',
    lat: 38.3269,
    lng: -109.8783,
  },
  {
    id: 'Capitol Reef',
    name: 'Capitol Reef',
    sub: 'UT',
    country: 'USA',
    lat: 38.367,
    lng: -111.2615,
  },
  {
    id: 'Carlsbad Caverns',
    name: 'Carlsbad Caverns',
    sub: 'NM',
    country: 'USA',
    lat: 32.1753,
    lng: -104.4439,
  },
  {
    id: 'Channel Islands',
    name: 'Channel Islands',
    sub: 'CA',
    country: 'USA',
    lat: 34.0069,
    lng: -119.7785,
  },
  { id: 'Congaree', name: 'Congaree', sub: 'SC', country: 'USA', lat: 33.7948, lng: -80.7821 },
  {
    id: 'Crater Lake',
    name: 'Crater Lake',
    sub: 'OR',
    country: 'USA',
    lat: 42.8684,
    lng: -122.1685,
  },
  {
    id: 'Cuyahoga Valley',
    name: 'Cuyahoga Valley',
    sub: 'OH',
    country: 'USA',
    lat: 41.2808,
    lng: -81.5678,
  },
  {
    id: 'Death Valley',
    name: 'Death Valley',
    sub: 'CA/NV',
    country: 'USA',
    lat: 36.5323,
    lng: -116.9325,
  },
  { id: 'Denali', name: 'Denali', sub: 'AK', country: 'USA', lat: 63.1148, lng: -151.1926 },
  {
    id: 'Dry Tortugas',
    name: 'Dry Tortugas',
    sub: 'FL',
    country: 'USA',
    lat: 24.6285,
    lng: -82.8733,
  },
  { id: 'Everglades', name: 'Everglades', sub: 'FL', country: 'USA', lat: 25.2866, lng: -80.8987 },
  {
    id: 'Gates of the Arctic',
    name: 'Gates of the Arctic',
    sub: 'AK',
    country: 'USA',
    lat: 67.7814,
    lng: -153.2994,
  },
  {
    id: 'Gateway Arch',
    name: 'Gateway Arch',
    sub: 'MO',
    country: 'USA',
    lat: 38.6247,
    lng: -90.1848,
  },
  { id: 'Glacier', name: 'Glacier', sub: 'MT', country: 'USA', lat: 48.7596, lng: -113.787 },
  {
    id: 'Glacier Bay',
    name: 'Glacier Bay',
    sub: 'AK',
    country: 'USA',
    lat: 58.6658,
    lng: -136.9002,
  },
  {
    id: 'Grand Canyon',
    name: 'Grand Canyon',
    sub: 'AZ',
    country: 'USA',
    lat: 36.0544,
    lng: -112.1401,
  },
  {
    id: 'Grand Teton',
    name: 'Grand Teton',
    sub: 'WY',
    country: 'USA',
    lat: 43.7904,
    lng: -110.6818,
  },
  {
    id: 'Great Basin',
    name: 'Great Basin',
    sub: 'NV',
    country: 'USA',
    lat: 38.9836,
    lng: -114.3013,
  },
  {
    id: 'Great Sand Dunes',
    name: 'Great Sand Dunes',
    sub: 'CO',
    country: 'USA',
    lat: 37.7916,
    lng: -105.5123,
  },
  {
    id: 'Great Smoky Mountains',
    name: 'Great Smoky Mountains',
    sub: 'TN/NC',
    country: 'USA',
    lat: 35.6131,
    lng: -83.4895,
  },
  {
    id: 'Guadalupe Mountains',
    name: 'Guadalupe Mountains',
    sub: 'TX',
    country: 'USA',
    lat: 31.9231,
    lng: -104.8608,
  },
  { id: 'Haleakalā', name: 'Haleakalā', sub: 'HI', country: 'USA', lat: 20.7013, lng: -156.1733 },
  {
    id: 'Hawaiʻi Volcanoes',
    name: 'Hawaiʻi Volcanoes',
    sub: 'HI',
    country: 'USA',
    lat: 19.4194,
    lng: -155.2885,
  },
  { id: 'Hot Springs', name: 'Hot Springs', sub: 'AR', country: 'USA', lat: 34.5199, lng: -93.055 },
  {
    id: 'Indiana Dunes',
    name: 'Indiana Dunes',
    sub: 'IN',
    country: 'USA',
    lat: 41.6533,
    lng: -87.0524,
  },
  {
    id: 'Isle Royale',
    name: 'Isle Royale',
    sub: 'MI',
    country: 'USA',
    lat: 47.9959,
    lng: -88.9093,
  },
  {
    id: 'Joshua Tree',
    name: 'Joshua Tree',
    sub: 'CA',
    country: 'USA',
    lat: 33.8734,
    lng: -115.901,
  },
  { id: 'Katmai', name: 'Katmai', sub: 'AK', country: 'USA', lat: 58.5079, lng: -154.9033 },
  {
    id: 'Kenai Fjords',
    name: 'Kenai Fjords',
    sub: 'AK',
    country: 'USA',
    lat: 59.9264,
    lng: -149.6535,
  },
  {
    id: 'Kings Canyon',
    name: 'Kings Canyon',
    sub: 'CA',
    country: 'USA',
    lat: 36.8879,
    lng: -118.5551,
  },
  {
    id: 'Kobuk Valley',
    name: 'Kobuk Valley',
    sub: 'AK',
    country: 'USA',
    lat: 67.5507,
    lng: -159.1223,
  },
  { id: 'Lake Clark', name: 'Lake Clark', sub: 'AK', country: 'USA', lat: 60.6144, lng: -154.1545 },
  {
    id: 'Lassen Volcanic',
    name: 'Lassen Volcanic',
    sub: 'CA',
    country: 'USA',
    lat: 40.4977,
    lng: -121.4207,
  },
  {
    id: 'Mammoth Cave',
    name: 'Mammoth Cave',
    sub: 'KY',
    country: 'USA',
    lat: 37.187,
    lng: -86.1005,
  },
  { id: 'Mesa Verde', name: 'Mesa Verde', sub: 'CO', country: 'USA', lat: 37.2309, lng: -108.4618 },
  {
    id: 'Mount Rainier',
    name: 'Mount Rainier',
    sub: 'WA',
    country: 'USA',
    lat: 46.8523,
    lng: -121.7603,
  },
  {
    id: 'New River Gorge',
    name: 'New River Gorge',
    sub: 'WV',
    country: 'USA',
    lat: 38.0722,
    lng: -81.0822,
  },
  {
    id: 'North Cascades',
    name: 'North Cascades',
    sub: 'WA',
    country: 'USA',
    lat: 48.7718,
    lng: -121.2985,
  },
  { id: 'Olympic', name: 'Olympic', sub: 'WA', country: 'USA', lat: 47.8021, lng: -123.6044 },
  {
    id: 'Petrified Forest',
    name: 'Petrified Forest',
    sub: 'AZ',
    country: 'USA',
    lat: 34.91,
    lng: -109.8068,
  },
  { id: 'Pinnacles', name: 'Pinnacles', sub: 'CA', country: 'USA', lat: 36.4906, lng: -121.1819 },
  { id: 'Redwood', name: 'Redwood', sub: 'CA', country: 'USA', lat: 41.2132, lng: -124.0046 },
  {
    id: 'Rocky Mountain',
    name: 'Rocky Mountain',
    sub: 'CO',
    country: 'USA',
    lat: 40.3428,
    lng: -105.6836,
  },
  { id: 'Saguaro', name: 'Saguaro', sub: 'AZ', country: 'USA', lat: 32.1471, lng: -110.7005 },
  { id: 'Sequoia', name: 'Sequoia', sub: 'CA', country: 'USA', lat: 36.4864, lng: -118.5658 },
  { id: 'Shenandoah', name: 'Shenandoah', sub: 'VA', country: 'USA', lat: 38.2928, lng: -78.6796 },
  {
    id: 'Theodore Roosevelt',
    name: 'Theodore Roosevelt',
    sub: 'ND',
    country: 'USA',
    lat: 46.979,
    lng: -103.5387,
  },
  {
    id: 'Virgin Islands',
    name: 'Virgin Islands',
    sub: 'VI',
    country: 'USA',
    lat: 18.3368,
    lng: -64.7333,
  },
  { id: 'Voyageurs', name: 'Voyageurs', sub: 'MN', country: 'USA', lat: 48.4841, lng: -92.8271 },
  {
    id: 'White Sands',
    name: 'White Sands',
    sub: 'NM',
    country: 'USA',
    lat: 32.7872,
    lng: -106.3257,
  },
  { id: 'Wind Cave', name: 'Wind Cave', sub: 'SD', country: 'USA', lat: 43.57, lng: -103.4794 },
  {
    id: 'Wrangell–St. Elias',
    name: 'Wrangell–St. Elias',
    sub: 'AK',
    country: 'USA',
    lat: 61.7104,
    lng: -142.985,
  },
  {
    id: 'Yellowstone',
    name: 'Yellowstone',
    sub: 'WY/MT/ID',
    country: 'USA',
    lat: 44.428,
    lng: -110.5885,
  },
  { id: 'Yosemite', name: 'Yosemite', sub: 'CA', country: 'USA', lat: 37.8651, lng: -119.5383 },
  { id: 'Zion', name: 'Zion', sub: 'UT', country: 'USA', lat: 37.2982, lng: -113.0263 },
  // Major Canadian National Parks
  { id: 'Banff', name: 'Banff', sub: 'AB', country: 'Canada', lat: 51.4968, lng: -115.9281 },
  { id: 'Jasper', name: 'Jasper', sub: 'AB', country: 'Canada', lat: 52.8737, lng: -118.0813 },
  { id: 'Yoho', name: 'Yoho', sub: 'BC', country: 'Canada', lat: 51.4633, lng: -116.5861 },
  { id: 'Kootenay', name: 'Kootenay', sub: 'BC', country: 'Canada', lat: 50.883, lng: -116.0427 },
  {
    id: 'Waterton Lakes',
    name: 'Waterton Lakes',
    sub: 'AB',
    country: 'Canada',
    lat: 49.0503,
    lng: -113.916,
  },
  {
    id: 'Pacific Rim',
    name: 'Pacific Rim',
    sub: 'BC',
    country: 'Canada',
    lat: 49.0667,
    lng: -125.7167,
  },
  {
    id: 'Glacier (Can)',
    name: 'Glacier (Can)',
    sub: 'BC',
    country: 'Canada',
    lat: 51.3,
    lng: -117.5167,
  },
  {
    id: 'Mount Revelstoke',
    name: 'Mount Revelstoke',
    sub: 'BC',
    country: 'Canada',
    lat: 51.0833,
    lng: -118.1667,
  },
  { id: 'Fundy', name: 'Fundy', sub: 'NB', country: 'Canada', lat: 45.6167, lng: -64.95 },
  {
    id: 'Gros Morne',
    name: 'Gros Morne',
    sub: 'NL',
    country: 'Canada',
    lat: 49.6833,
    lng: -57.7333,
  },
  {
    id: 'Cape Breton Highlands',
    name: 'Cape Breton Highlands',
    sub: 'NS',
    country: 'Canada',
    lat: 46.7167,
    lng: -60.65,
  },
  {
    id: 'Prince Edward Island',
    name: 'Prince Edward Island',
    sub: 'PE',
    country: 'Canada',
    lat: 46.4167,
    lng: -63.0833,
  },
  {
    id: 'Bruce Peninsula',
    name: 'Bruce Peninsula',
    sub: 'ON',
    country: 'Canada',
    lat: 45.2167,
    lng: -81.5333,
  },
  {
    id: 'Point Pelee',
    name: 'Point Pelee',
    sub: 'ON',
    country: 'Canada',
    lat: 41.9667,
    lng: -82.5167,
  },
  { id: 'Rouge', name: 'Rouge', sub: 'ON', country: 'Canada', lat: 43.829, lng: -79.176 },
  {
    id: 'Grasslands',
    name: 'Grasslands',
    sub: 'SK',
    country: 'Canada',
    lat: 49.1167,
    lng: -107.4167,
  },
  {
    id: 'Prince Albert',
    name: 'Prince Albert',
    sub: 'SK',
    country: 'Canada',
    lat: 53.9167,
    lng: -106.3667,
  },
  {
    id: 'Riding Mountain',
    name: 'Riding Mountain',
    sub: 'MB',
    country: 'Canada',
    lat: 50.8833,
    lng: -100.0333,
  },
  { id: 'Nahanni', name: 'Nahanni', sub: 'NT', country: 'Canada', lat: 61.5833, lng: -125.8333 },
  {
    id: 'Wood Buffalo',
    name: 'Wood Buffalo',
    sub: 'AB/NT',
    country: 'Canada',
    lat: 59.3833,
    lng: -112.9833,
  },
  { id: 'Kluane', name: 'Kluane', sub: 'YT', country: 'Canada', lat: 60.75, lng: -138.5 },
  { id: 'Auyuittuq', name: 'Auyuittuq', sub: 'NU', country: 'Canada', lat: 66.8833, lng: -65.1667 },
];

export const STATES: GeoLocation[] = [
  {
    id: 'Alabama',
    name: 'Alabama',
    sub: 'USA',
    capital: 'Montgomery',
    lat: 32.3668,
    lng: -86.3006,
  },
  { id: 'Alaska', name: 'Alaska', sub: 'USA', capital: 'Juneau', lat: 58.3019, lng: -134.4197 },
  { id: 'Arizona', name: 'Arizona', sub: 'USA', capital: 'Phoenix', lat: 33.4484, lng: -112.074 },
  {
    id: 'Arkansas',
    name: 'Arkansas',
    sub: 'USA',
    capital: 'Little Rock',
    lat: 34.7465,
    lng: -92.2896,
  },
  {
    id: 'California',
    name: 'California',
    sub: 'USA',
    capital: 'Sacramento',
    lat: 38.5816,
    lng: -121.4944,
  },
  { id: 'Colorado', name: 'Colorado', sub: 'USA', capital: 'Denver', lat: 39.7392, lng: -104.9903 },
  {
    id: 'Connecticut',
    name: 'Connecticut',
    sub: 'USA',
    capital: 'Hartford',
    lat: 41.7637,
    lng: -72.6851,
  },
  { id: 'Delaware', name: 'Delaware', sub: 'USA', capital: 'Dover', lat: 39.1582, lng: -75.5244 },
  {
    id: 'Florida',
    name: 'Florida',
    sub: 'USA',
    capital: 'Tallahassee',
    lat: 30.4383,
    lng: -84.2807,
  },
  { id: 'Georgia', name: 'Georgia', sub: 'USA', capital: 'Atlanta', lat: 33.749, lng: -84.388 },
  { id: 'Hawaii', name: 'Hawaii', sub: 'USA', capital: 'Honolulu', lat: 21.3069, lng: -157.8583 },
  { id: 'Idaho', name: 'Idaho', sub: 'USA', capital: 'Boise', lat: 43.615, lng: -116.2023 },
  {
    id: 'Illinois',
    name: 'Illinois',
    sub: 'USA',
    capital: 'Springfield',
    lat: 39.7817,
    lng: -89.6501,
  },
  {
    id: 'Indiana',
    name: 'Indiana',
    sub: 'USA',
    capital: 'Indianapolis',
    lat: 39.7684,
    lng: -86.1581,
  },
  { id: 'Iowa', name: 'Iowa', sub: 'Iowa', capital: 'Des Moines', lat: 41.5868, lng: -93.625 },
  { id: 'Kansas', name: 'Kansas', sub: 'USA', capital: 'Topeka', lat: 39.0473, lng: -95.6752 },
  {
    id: 'Kentucky',
    name: 'Kentucky',
    sub: 'USA',
    capital: 'Frankfort',
    lat: 38.1973,
    lng: -84.8733,
  },
  {
    id: 'Louisiana',
    name: 'Louisiana',
    sub: 'USA',
    capital: 'Baton Rouge',
    lat: 30.4515,
    lng: -91.1871,
  },
  { id: 'Maine', name: 'Maine', sub: 'USA', capital: 'Augusta', lat: 44.3106, lng: -69.7795 },
  {
    id: 'Maryland',
    name: 'Maryland',
    sub: 'USA',
    capital: 'Annapolis',
    lat: 38.9784,
    lng: -76.4922,
  },
  {
    id: 'Massachusetts',
    name: 'Massachusetts',
    sub: 'USA',
    capital: 'Boston',
    lat: 42.3601,
    lng: -71.0589,
  },
  { id: 'Michigan', name: 'Michigan', sub: 'USA', capital: 'Lansing', lat: 42.7325, lng: -84.5555 },
  {
    id: 'Minnesota',
    name: 'Minnesota',
    sub: 'USA',
    capital: 'St. Paul',
    lat: 44.9537,
    lng: -93.09,
  },
  {
    id: 'Mississippi',
    name: 'Mississippi',
    sub: 'USA',
    capital: 'Jackson',
    lat: 32.2988,
    lng: -90.1848,
  },
  {
    id: 'Missouri',
    name: 'Missouri',
    sub: 'USA',
    capital: 'Jefferson City',
    lat: 38.5767,
    lng: -92.1735,
  },
  { id: 'Montana', name: 'Montana', sub: 'USA', capital: 'Helena', lat: 46.5891, lng: -112.0391 },
  { id: 'Nebraska', name: 'Nebraska', sub: 'USA', capital: 'Lincoln', lat: 40.8136, lng: -96.7026 },
  {
    id: 'Nevada',
    name: 'Nevada',
    sub: 'USA',
    capital: 'Carson City',
    lat: 39.1638,
    lng: -119.7674,
  },
  {
    id: 'New Hampshire',
    name: 'New Hampshire',
    sub: 'USA',
    capital: 'Concord',
    lat: 43.2081,
    lng: -71.5375,
  },
  {
    id: 'New Jersey',
    name: 'New Jersey',
    sub: 'USA',
    capital: 'Trenton',
    lat: 40.217,
    lng: -74.7429,
  },
  {
    id: 'New Mexico',
    name: 'New Mexico',
    sub: 'USA',
    capital: 'Santa Fe',
    lat: 35.687,
    lng: -105.9378,
  },
  { id: 'New York', name: 'New York', sub: 'USA', capital: 'Albany', lat: 42.6526, lng: -73.7562 },
  {
    id: 'North Carolina',
    name: 'North Carolina',
    sub: 'USA',
    capital: 'Raleigh',
    lat: 35.7796,
    lng: -78.6382,
  },
  {
    id: 'North Dakota',
    name: 'North Dakota',
    sub: 'USA',
    capital: 'Bismarck',
    lat: 46.8083,
    lng: -100.7837,
  },
  { id: 'Ohio', name: 'Ohio', sub: 'USA', capital: 'Columbus', lat: 39.9612, lng: -82.9988 },
  {
    id: 'Oklahoma',
    name: 'Oklahoma',
    sub: 'USA',
    capital: 'Oklahoma City',
    lat: 35.4676,
    lng: -97.5164,
  },
  { id: 'Oregon', name: 'Oregon', sub: 'USA', capital: 'Salem', lat: 44.9429, lng: -123.0351 },
  {
    id: 'Pennsylvania',
    name: 'Pennsylvania',
    sub: 'USA',
    capital: 'Harrisburg',
    lat: 40.2732,
    lng: -76.8867,
  },
  {
    id: 'Rhode Island',
    name: 'Rhode Island',
    sub: 'USA',
    capital: 'Providence',
    lat: 41.824,
    lng: -71.4128,
  },
  {
    id: 'South Carolina',
    name: 'South Carolina',
    sub: 'USA',
    capital: 'Columbia',
    lat: 34.0007,
    lng: -81.0348,
  },
  {
    id: 'South Dakota',
    name: 'South Dakota',
    sub: 'USA',
    capital: 'Pierre',
    lat: 44.3668,
    lng: -100.3538,
  },
  {
    id: 'Tennessee',
    name: 'Tennessee',
    sub: 'USA',
    capital: 'Nashville',
    lat: 36.1627,
    lng: -86.7816,
  },
  { id: 'Texas', name: 'Texas', sub: 'USA', capital: 'Austin', lat: 30.2672, lng: -97.7431 },
  { id: 'Utah', name: 'Utah', sub: 'USA', capital: 'Salt Lake City', lat: 40.7608, lng: -111.891 },
  {
    id: 'Vermont',
    name: 'Vermont',
    sub: 'USA',
    capital: 'Montpelier',
    lat: 44.2601,
    lng: -72.5754,
  },
  { id: 'Virginia', name: 'Virginia', sub: 'USA', capital: 'Richmond', lat: 37.5407, lng: -77.436 },
  {
    id: 'Washington',
    name: 'Washington',
    sub: 'USA',
    capital: 'Olympia',
    lat: 47.0378,
    lng: -122.9007,
  },
  {
    id: 'West Virginia',
    name: 'West Virginia',
    sub: 'USA',
    capital: 'Charleston',
    lat: 38.3498,
    lng: -81.6326,
  },
  {
    id: 'Wisconsin',
    name: 'Wisconsin',
    sub: 'USA',
    capital: 'Madison',
    lat: 43.0731,
    lng: -89.4012,
  },
  { id: 'Wyoming', name: 'Wyoming', sub: 'USA', capital: 'Cheyenne', lat: 41.14, lng: -104.8202 },
  {
    id: 'Alberta',
    name: 'Alberta',
    sub: 'Canada',
    capital: 'Edmonton',
    lat: 53.5461,
    lng: -113.4938,
  },
  {
    id: 'British Columbia',
    name: 'British Columbia',
    sub: 'Canada',
    capital: 'Victoria',
    lat: 48.4284,
    lng: -123.3656,
  },
  {
    id: 'Manitoba',
    name: 'Manitoba',
    sub: 'Canada',
    capital: 'Winnipeg',
    lat: 49.8951,
    lng: -97.1384,
  },
  {
    id: 'New Brunswick',
    name: 'New Brunswick',
    sub: 'Canada',
    capital: 'Fredericton',
    lat: 45.9636,
    lng: -66.6431,
  },
  {
    id: 'Newfoundland and Labrador',
    name: 'Newfoundland and Labrador',
    sub: 'Canada',
    capital: "St. John's",
    lat: 47.5615,
    lng: -52.7126,
  },
  {
    id: 'Nova Scotia',
    name: 'Nova Scotia',
    sub: 'Canada',
    capital: 'Halifax',
    lat: 44.6488,
    lng: -63.5752,
  },
  {
    id: 'Ontario',
    name: 'Ontario',
    sub: 'Canada',
    capital: 'Toronto',
    lat: 43.6532,
    lng: -79.3832,
  },
  {
    id: 'Prince Edward Island',
    name: 'Prince Edward Island',
    sub: 'Canada',
    capital: 'Charlottetown',
    lat: 46.2382,
    lng: -63.1311,
  },
  {
    id: 'Quebec',
    name: 'Quebec',
    sub: 'Canada',
    capital: 'Quebec City',
    lat: 46.8139,
    lng: -71.2082,
  },
  {
    id: 'Saskatchewan',
    name: 'Saskatchewan',
    sub: 'Canada',
    capital: 'Regina',
    lat: 50.4452,
    lng: -104.6189,
  },
  {
    id: 'Northwest Territories',
    name: 'Northwest Territories',
    sub: 'Canada',
    capital: 'Yellowknife',
    lat: 62.454,
    lng: -114.3718,
  },
  { id: 'Nunavut', name: 'Nunavut', sub: 'Canada', capital: 'Iqaluit', lat: 63.7467, lng: -68.517 },
  {
    id: 'Yukon',
    name: 'Yukon',
    sub: 'Canada',
    capital: 'Whitehorse',
    lat: 60.7212,
    lng: -135.0568,
  },
];
