export type ColorThemeId =
  | 'dunes-deep-lake'
  | 'classic-stone'
  | 'forest-ranger'
  | 'midnight-slate'
  | 'desert-sunset'
  | 'lake-forest'
  | 'dutch-orange'
  | 'alpine-orange';

export interface ColorThemeDefinition {
  id: ColorThemeId;
  name: string;
  description: string;
  fontName: string;
  fontFamily: string;
  swatches: [string, string, string]; // [headerBg, canvasBg, accentColor]
  canvasBg: string;
  headerBg: string;
  headerText: string;
  headerBorder: string;
  cardBg: string;
  cardBorder: string;
  toolbarBg: string;
  accent: string;
  isDark?: boolean;
  textColor: string;
  subtextColor: string;
  // Button styling tokens
  buttonBg: string;
  buttonBorder: string;
  buttonText: string;
  buttonHoverBg: string;
  buttonActiveBg: string;
  buttonActiveText: string;
  // State polygon shading tokens
  stateVisitedFill: string;
  stateVisitedStroke: string;
  statePartialFill: string;
  statePartialStroke: string;
  stateUnvisitedFill: string;
  stateUnvisitedStroke: string;
  // Location marker glyph background tokens
  markerVisitedColor: string;
  markerPartialColor: string;
  markerUnvisitedColor: string;
}

export const COLOR_THEMES: Record<ColorThemeId, ColorThemeDefinition> = {
  'dunes-deep-lake': {
    id: 'dunes-deep-lake',
    name: 'Dunes & Deep Lake',
    description: 'Lake Michigan navy blue with warm natural dune sandstone',
    fontName: 'Outfit',
    fontFamily: "'Outfit', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    swatches: ['#16384c', '#f5eee6', '#b4533c'],
    canvasBg: '#f5eee6',
    headerBg: '#16384c',
    headerText: '#ffffff',
    headerBorder: '#102b3b',
    cardBg: '#ffffff',
    cardBorder: '#e6ded4',
    toolbarBg: '#ffffff',
    accent: '#16384c',
    textColor: '#1c1917',
    subtextColor: '#78716c',
    buttonBg: '#fdfbf7',
    buttonBorder: '#dfd4c7',
    buttonText: '#16384c',
    buttonHoverBg: '#f5eee6',
    buttonActiveBg: '#16384c',
    buttonActiveText: '#ffffff',
    stateVisitedFill: '#16384c',
    stateVisitedStroke: '#0f2837',
    statePartialFill: '#b4533c',
    statePartialStroke: '#923e2b',
    stateUnvisitedFill: '#d6d3d1',
    stateUnvisitedStroke: '#cbd5e1',
    markerVisitedColor: '#16384c',
    markerPartialColor: '#b4533c',
    markerUnvisitedColor: '#94a3b8',
  },
  'classic-stone': {
    id: 'classic-stone',
    name: 'Classic Stone & Clean Slate',
    description: 'Clean stone canvas with crisp white cards and emerald accents',
    fontName: 'Inter',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
    swatches: ['#ffffff', '#fafaf9', '#16a34a'],
    canvasBg: '#fafaf9',
    headerBg: '#ffffff',
    headerText: '#1c1917',
    headerBorder: '#e7e5e4',
    cardBg: '#ffffff',
    cardBorder: '#e7e5e4',
    toolbarBg: '#ffffff',
    accent: '#16a34a',
    textColor: '#1c1917',
    subtextColor: '#78716c',
    buttonBg: '#fcfbf9',
    buttonBorder: '#e7e5e4',
    buttonText: '#1c1917',
    buttonHoverBg: '#f5f5f4',
    buttonActiveBg: '#16a34a',
    buttonActiveText: '#ffffff',
    stateVisitedFill: '#16a34a',
    stateVisitedStroke: '#15803d',
    statePartialFill: '#f59e0b',
    statePartialStroke: '#d97706',
    stateUnvisitedFill: '#d6d3d1',
    stateUnvisitedStroke: '#cbd5e1',
    markerVisitedColor: '#16a34a',
    markerPartialColor: '#f59e0b',
    markerUnvisitedColor: '#94a3b8',
  },
  'forest-ranger': {
    id: 'forest-ranger',
    name: 'Sage & Forest Ranger',
    description: 'Deep national park evergreen with soothing sage mist canvas',
    fontName: 'Albert Sans',
    fontFamily: "'Albert Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    swatches: ['#1e3a2f', '#ebeee6', '#2d6a4f'],
    canvasBg: '#ebeee6',
    headerBg: '#1e3a2f',
    headerText: '#ffffff',
    headerBorder: '#162c23',
    cardBg: '#fcfdfa',
    cardBorder: '#d4ded7',
    toolbarBg: '#fcfdfa',
    accent: '#1e3a2f',
    textColor: '#1c1917',
    subtextColor: '#57534e',
    buttonBg: '#f2f5ee',
    buttonBorder: '#cedbd1',
    buttonText: '#1e3a2f',
    buttonHoverBg: '#e5ede4',
    buttonActiveBg: '#1e3a2f',
    buttonActiveText: '#ffffff',
    stateVisitedFill: '#2d6a4f',
    stateVisitedStroke: '#1e4634',
    statePartialFill: '#d97706',
    statePartialStroke: '#b45309',
    stateUnvisitedFill: '#cbd5e1',
    stateUnvisitedStroke: '#94a3b8',
    markerVisitedColor: '#2d6a4f',
    markerPartialColor: '#d97706',
    markerUnvisitedColor: '#8ba195',
  },
  'midnight-slate': {
    id: 'midnight-slate',
    name: 'Midnight Slate (Dark)',
    description: 'Immersive dark cartography with luminous blue highlights',
    fontName: 'Space Grotesk',
    fontFamily: "'Space Grotesk', -apple-system, BlinkMacSystemFont, monospace, sans-serif",
    swatches: ['#1e293b', '#0f172a', '#38bdf8'],
    canvasBg: '#0f172a',
    headerBg: '#1e293b',
    headerText: '#f8fafc',
    headerBorder: '#334155',
    cardBg: '#1e293b',
    cardBorder: '#334155',
    toolbarBg: '#1e293b',
    accent: '#38bdf8',
    isDark: true,
    textColor: '#f8fafc',
    subtextColor: '#94a3b8',
    buttonBg: '#0f172a',
    buttonBorder: '#334155',
    buttonText: '#f1f5f9',
    buttonHoverBg: '#1e293b',
    buttonActiveBg: '#38bdf8',
    buttonActiveText: '#0f172a',
    stateVisitedFill: '#0284c7',
    stateVisitedStroke: '#38bdf8',
    statePartialFill: '#f59e0b',
    statePartialStroke: '#fbbf24',
    stateUnvisitedFill: '#334155',
    stateUnvisitedStroke: '#475569',
    markerVisitedColor: '#38bdf8',
    markerPartialColor: '#fbbf24',
    markerUnvisitedColor: '#64748b',
  },
  'desert-sunset': {
    id: 'desert-sunset',
    name: 'Terracotta & Sandstone',
    description: 'Warm Southwest red rock clay and sunbaked parchment linen',
    fontName: 'Plus Jakarta Sans',
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    swatches: ['#a84325', '#f6f1ea', '#d97706'],
    canvasBg: '#f6f1ea',
    headerBg: '#a84325',
    headerText: '#ffffff',
    headerBorder: '#88351c',
    cardBg: '#fdfcf9',
    cardBorder: '#e7dfd5',
    toolbarBg: '#fdfcf9',
    accent: '#a84325',
    textColor: '#1c1917',
    subtextColor: '#78716c',
    buttonBg: '#f9f3ec',
    buttonBorder: '#e4d5c5',
    buttonText: '#88351c',
    buttonHoverBg: '#f1e4d4',
    buttonActiveBg: '#a84325',
    buttonActiveText: '#ffffff',
    stateVisitedFill: '#c2410c',
    stateVisitedStroke: '#9a3412',
    statePartialFill: '#d97706',
    statePartialStroke: '#b45309',
    stateUnvisitedFill: '#d6d3d1',
    stateUnvisitedStroke: '#cbd5e1',
    markerVisitedColor: '#c2410c',
    markerPartialColor: '#d97706',
    markerUnvisitedColor: '#94a3b8',
  },
  'lake-forest': {
    id: 'lake-forest',
    name: 'Lake Michigan & Forest',
    description: 'Deep lake water blue with soft forest mist and pine accents',
    fontName: 'DM Sans',
    fontFamily: "'DM Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    swatches: ['#144265', '#dce8e1', '#1e5138'],
    canvasBg: '#dce8e1',
    headerBg: '#144265',
    headerText: '#ffffff',
    headerBorder: '#0f334f',
    cardBg: '#ffffff',
    cardBorder: '#cde0d6',
    toolbarBg: '#ffffff',
    accent: '#1e5138',
    textColor: '#0f172a',
    subtextColor: '#475569',
    buttonBg: '#eef5f0',
    buttonBorder: '#c4ded0',
    buttonText: '#144265',
    buttonHoverBg: '#e0ece3',
    buttonActiveBg: '#144265',
    buttonActiveText: '#ffffff',
    stateVisitedFill: '#144265',
    stateVisitedStroke: '#0d2e47',
    statePartialFill: '#1e5138',
    statePartialStroke: '#143a28',
    stateUnvisitedFill: '#cbd5e1',
    stateUnvisitedStroke: '#94a3b8',
    markerVisitedColor: '#144265',
    markerPartialColor: '#1e5138',
    markerUnvisitedColor: '#94a3b8',
  },
  'dutch-orange': {
    id: 'dutch-orange',
    name: 'Vibrant Dutch Orange',
    description: 'Celebratory rich Dutch orange with warm linen cream canvas',
    fontName: 'Urbanist',
    fontFamily: "'Urbanist', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    swatches: ['#ea580c', '#fbf7f0', '#245a44'],
    canvasBg: '#fbf7f0',
    headerBg: '#ea580c',
    headerText: '#ffffff',
    headerBorder: '#c2410c',
    cardBg: '#ffffff',
    cardBorder: '#ebdcd0',
    toolbarBg: '#ffffff',
    accent: '#ea580c',
    textColor: '#1c1917',
    subtextColor: '#78716c',
    buttonBg: '#fef8f3',
    buttonBorder: '#f0d6c4',
    buttonText: '#9a3412',
    buttonHoverBg: '#faebe0',
    buttonActiveBg: '#ea580c',
    buttonActiveText: '#ffffff',
    stateVisitedFill: '#ea580c',
    stateVisitedStroke: '#c2410c',
    statePartialFill: '#245a44',
    statePartialStroke: '#1a4131',
    stateUnvisitedFill: '#d6d3d1',
    stateUnvisitedStroke: '#cbd5e1',
    markerVisitedColor: '#ea580c',
    markerPartialColor: '#245a44',
    markerUnvisitedColor: '#94a3b8',
  },
  'alpine-orange': {
    id: 'alpine-orange',
    name: 'Alpine Pine & Dutch Accent',
    description: 'Crisp alpine pine mist with bold Dutch orange banner',
    fontName: 'Outfit',
    fontFamily: "'Outfit', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    swatches: ['#ea580c', '#e5ece7', '#1b663e'],
    canvasBg: '#e5ece7',
    headerBg: '#ea580c',
    headerText: '#ffffff',
    headerBorder: '#c2410c',
    cardBg: '#ffffff',
    cardBorder: '#d1ddd5',
    toolbarBg: '#ffffff',
    accent: '#1b663e',
    textColor: '#1c1917',
    subtextColor: '#57534e',
    buttonBg: '#edf4ef',
    buttonBorder: '#cbded1',
    buttonText: '#1b663e',
    buttonHoverBg: '#dbeadd',
    buttonActiveBg: '#ea580c',
    buttonActiveText: '#ffffff',
    stateVisitedFill: '#1b663e',
    stateVisitedStroke: '#134e2e',
    statePartialFill: '#ea580c',
    statePartialStroke: '#c2410c',
    stateUnvisitedFill: '#cbd5e1',
    stateUnvisitedStroke: '#94a3b8',
    markerVisitedColor: '#1b663e',
    markerPartialColor: '#ea580c',
    markerUnvisitedColor: '#94a3b8',
  },
};

export const DEFAULT_THEME_ID: ColorThemeId = 'dunes-deep-lake';
export const AVAILABLE_THEMES_LIST: ColorThemeDefinition[] = Object.values(COLOR_THEMES);
